mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.views.generic import RedirectView


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.StudioLoginView.as_view(), name='login'),
    path('logout/', views.StudioLogoutView.as_view(), name='logout'),
    path('accounts/profile/', views.profile, name='profile'),
    path('service/<int:id>/', views.SepServiceView.as_view(), name='separate_service'),
    path('order/<int:service_id>/', views.order_service, name='order_service'),
    path('services/all/', views.services_all, name='services_all'),
    path('search/', views.search_service, name='search'),
]

polls/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, FileExtensionValidator
from django.db import models
from django.dispatch import Signal
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string


def get_name_file(instance, filename):
    return 'mysite/file'.join([get_random_string(5) + '_' + filename])


class Service(models.Model):
    service_name = models.CharField(max_length=200, verbose_name='Название опроса')
    service_date = models.DateTimeField('date published')
    description_service = models.CharField(max_length=200, verbose_name='Краткое описание')
    service_img = models.ImageField(verbose_name='Картинка', upload_to=get_name_file, blank=True, null=True, validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    user = models.ForeignKey('User', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.service_name

class User(AbstractUser):
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True, blank=False, validators=[
        RegexValidator(
            regex='^[A-Za-z -]*$',
            message='Имя пользователя должно состоять только из латиницы',
            code='invalid_username'
        ),
    ])
    avatar = models.ImageField(upload_to=get_name_file, verbose_name='Аватар', blank=False, null=True, validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    password = models.CharField(max_length=200, verbose_name='Пароль', blank=False)

    class Meta:
        ordering = ['username', 'avatar', 'password']

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username


user_registrated = Signal()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ordered_services = models.ManyToManyField(Service)





class Order(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    service = models.ForeignKey('Service', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.service.service_name}"

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User, Service, Order
from .models import user_registrated
from django.contrib.auth.forms import AuthenticationForm


class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput, help_text='Повторите тот же самый пароль еще раз')

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = User
        fields = ('username', 'avatar')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Введите логин', widget=forms.TextInput)
    password = forms.CharField(label='Введите пароль', widget=forms.PasswordInput)

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, get_object_or_404
from .models import User, Service, Order
from django.views import generic
from .forms import RegisterUserForm
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import HttpResponseBadRequest


def index(request):
    service_list = Service.objects.order_by('-service_date')[:5]
    return render(request, 'index.html', {'service_list': service_list})


def my_services(request):
    service_list = Service.objects.filter(username=request.user)
    return render(request, 'polls/service_list.html', {'service_list': service_list})

def services_all(request):
    service_list = Service.objects.all()
    return render(request, 'polls/services_all.html', {'service_list': service_list})


class SepServiceView(generic.DetailView):
    pk_url_kwarg = 'id'
    model = Service
    template_name = 'polls/separate_service.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user, service=self.object)
        return context

    def post(self, request, *args, **kwargs):
        service = self.get_object()
        order = Order(user=request.user, service=service)
        order.save()
        messages.success(request, 'Услуга/товар успешно заказана')
        return redirect('polls:profile')



def order_service(request, service_id):
    # Получаем объект услуги/товара по его идентификатору
    try:
        service = Service.objects.get(id=service_id)
    except Service.DoesNotExist:
        return HttpResponseBadRequest('Услуга/товар не найден')

    # Проверяем, является ли пользователь авторизованным
    if not request.user.is_authenticated:
        return HttpResponseBadRequest('Пользователь не авторизован')

    else:
        # Добавляем услугу/товар в список заказанных услуг/товаров текущего пользователя
        order = Order(user=request.user, service=service)
        order.save()
        messages.success(request, 'Услуга/товар успешно заказана')

        # Перенаправляем на страницу профиля пользователя
        return redirect('polls:profile')


class StudioLoginView(LoginView):
    template_name = 'registration/login.html'


class StudioLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'registration/login.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('polls:index')


@login_required
def profile(request):
    current_user = request.user
    service_list = Order.objects.filter(user=current_user)
    context = {'service_list': service_list}
    return render(request, 'registration/profile.html', context)

def search_service(request):
    query = request.GET.get('query', '')
    results = []

    if query:
        results = Service.objects.filter(service_name__icontains=query)

    context = {'results': results}
    return render(request, "polls/service_search.html", context)

polls/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %} - сайт визитка </title>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
        <p class="mr-md-auto p-2">Firma</p>
        {% if user.is_authenticated %}
        <div>
            <a class="p-2 text-dark" href="{% url 'polls:index' %}">Главная</a>
            <a class="p-2 text-dark" href="{% url 'polls:services_all' %}">Услуги/товары</a>
            <a class="p-2 text-dark" href="{% url 'polls:profile' %}">Профиль</a>
            <a class="p-2 text-dark" href="{% url 'polls:logout' %}">Выход</a>
        </div>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'polls:index' %}">Главная</a>
            <a class="p-2 text-dark" href="{% url 'polls:services_all' %}">Товары/услуги</a>
            <a class="p-2 text-dark" href="{% url 'polls:register' %}">Регистрация</a>
            <a class="p-2 text-dark" href="{% url 'polls:login' %}">Вход</a>
        {% endif %}
    </div>
    <div class="row">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</div>

</body>
</html>

polls/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if service_list %}
<h2>Последние 5 услуг/товаров</h2>
<form class="form form-search" method="get" action="{% url 'polls:search' %}">
    <input type="search" placeholder="Поиск" name="query">
    <button type="submit">Поиск</button>
</form>
<ul>
    {% for service in service_list %}
    <div class="card" style="width: 18rem;">
        <img src="/media/{{ service.service_img }}" class="card-img-top" alt="Изображение">
        <div class="card-body">
          <a href="{% url 'polls:separate_service' service.id %}">Название: {{ service.service_name }}</a>
          <p>Описание: {{ service.description_service }} </p>
        </div>
      </div>
    {% endfor %}
</ul>
{% else %}
<p>
    Нет услуг/товаров!
</p>
{% endif %}
{% endblock %}

polls/templates/polls/separate_service.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Услуга/товар: {{ service.service_name }}</h2>
<div class="card" style="width: 18rem;">
    <img src="/media/{{ service.service_img }}" class="card-img-top" alt="Изображение">
    <div class="card-body">
        <a>Название: {{ service.service_name }}</a>
        <p>Описание: {{ service.description_service }} </p>
    </div>
</div>
<form method="post" action="{% url 'polls:order_service' service.id %}">
    {% csrf_token %}
    <input type="submit" value="Заказать услугу/товар">
</form>
{% endblock %}

polls/templates/polls/service_list.html
{% extends "base.html" %}
{% block content %}
<h2>Мои услуги/товары</h2>
{% if service_list %}
<ul>
  {% for service in service_list %}
      <div class="card" style="width: 18rem;">
        <img src="/media/{{ service.service_img }}" class="card-img-top" alt="Изображение">
        <div class="card-body">
          <p>Название: {{ service.service_name }}</p>
          <p>Описание: {{ service.description_service }} </p>
        </div>
      </div>
  {% endfor %}
</ul>
{% else %}
  <p>У вас нет услуг/товаров</p>
{% endif %}
{% endblock %}

polls/templates/polls/service_search.html
{% extends "base.html" %}

{% block content %}
<form class="form form-search" method="get" action="{% url 'polls:search' %}">
    <input type="search" placeholder="Поиск" name="query">
    <button type="submit">Поиск</button>
</form>
{% if results %}
<div class="cards">
    {% for service in results %}
    <div class="card" style="width: 18rem;">
        <img src="/media/{{ service.service_img }}" class="card-img-top" alt="Изображение">
        <div class="card-body">
          <a href="{% url 'polls:separate_service' service.id %}">Название: {{ service.service_name }}</a>
          <p>Описание: {{ service.description_service }} </p>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <h2 class="card-title">Нет результатов для отображения</h2>
{% endif %}
{% endblock %}

polls/templates/polls/services_all.html
{% extends "base.html" %}
{% block content %}
<h2>Все услуги/товары</h2>
<form class="form form-search" method="get" action="{% url 'polls:search' %}">
    <input type="search" placeholder="Поиск" name="query">
    <button type="submit">Поиск</button>
</form>
{% if service_list %}
<ul>
  {% for service in service_list %}
      <div class="card" style="width: 18rem;">
        <img src="/media/{{ service.service_img }}" class="card-img-top" alt="Изображение">
        <div class="card-body">
          <a href="{% url 'polls:separate_service' service.id %}">Название: {{ service.service_name }}</a>
          <p>Описание: {{ service.description_service }} </p>
        </div>
      </div>
  {% endfor %}
</ul>
{% else %}
  <p>Нет услуг/товаров</p>
{% endif %}
{% endblock %}